// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQy1qFJ06GpyzmFjWWGMBAE3QRG0Kcyc',
    appId: '1:280734172453:web:ca5fd9d64e354f076d86cc',
    messagingSenderId: '280734172453',
    projectId: 'game-backlog-app-28900',
    authDomain: 'game-backlog-app-28900.firebaseapp.com',
    storageBucket: 'game-backlog-app-28900.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXO9Zw-A9Zj-9dDFMfYzT2B3KxVUMuPC4',
    appId: '1:280734172453:android:dbbb6c20dcc4bd566d86cc',
    messagingSenderId: '280734172453',
    projectId: 'game-backlog-app-28900',
    storageBucket: 'game-backlog-app-28900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5nKMeBnKlQEiOmm2Wt94UExscV0kzJQ',
    appId: '1:280734172453:ios:890f252ae09017376d86cc',
    messagingSenderId: '280734172453',
    projectId: 'game-backlog-app-28900',
    storageBucket: 'game-backlog-app-28900.appspot.com',
    iosClientId: '280734172453-u9roi2cvq94qan6sinfuhpuobiqgs15g.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameBacklogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH5nKMeBnKlQEiOmm2Wt94UExscV0kzJQ',
    appId: '1:280734172453:ios:890f252ae09017376d86cc',
    messagingSenderId: '280734172453',
    projectId: 'game-backlog-app-28900',
    storageBucket: 'game-backlog-app-28900.appspot.com',
    iosClientId: '280734172453-u9roi2cvq94qan6sinfuhpuobiqgs15g.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameBacklogApp',
  );
}
